### PR TITLE
Update AD endpoint in US government cloud

### PR DESCRIPTION
**Pull request by kpajdzik**
Corresponds to https://github.com/Azure/azure-sdk-for-node/commit/2cae18cc5d52c9eb8ce38e25f47126ed187546fd#diff-312a751ba50d2de2472f78dd7d9a5d8f

### CODE REVIEW

**Comment by RikkiGibson** [comment]
Please run a build and commit the files,

If you want to take a minute to remove the build products from git a-la Azure/ms-rest-js#37 that would be stellar. If you don't have the time to dive into that, that's perfectly OK :)

**Comment by kpajdzik** [comment]
I'll remove all generated files in another PR to keep history clean.

**Comment by kpajdzik** [comment]
Removed the file in this PR: https://github.com/Azure/ms-rest-azure-env/pull/7

**Comment by RikkiGibson** [comment]
It doesn't look like there's a `"prepare"` step in package.json (see the [npm-scripts documentation](https://docs.npmjs.com/misc/scripts)). This is fine while we're doing all our dev and publishing locally for this package, but eventually we'll want this package set up so that:

1. automated publishing runs predictably
2. install from a git repo causes build products to be produced at install time

**Comment by RikkiGibson** [comment]
I don't want to totally randomize you so don't drop what you're doing to gold-plate this package :)

**Comment by kpajdzik** [comment]
I've created an issue so I won't forget: https://github.com/Azure/ms-rest-azure-env/issues/8

**Pull request merged**
